docs:
  - year: 2016
    form_of_study: "budget"
    file_name: "03082016.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2016
    form_of_study: "budget"
    file_name: "08082016 бюджет.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2016
    form_of_study: "paid"
    file_name: "08082016p платное.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2016
    form_of_study: "paid"
    file_name: "31082016p платное.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2016
    form_of_study: "contract"
    file_name: "29072016 бви.pdf"
    regex:
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'

  - year: 2017
    form_of_study: "budget"
    file_name: "20170803 бюджет.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2017
    form_of_study: "budget"
    file_name: "20170808 бюджет.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2017
    form_of_study: "paid"
    file_name: "20170808_p_ платное.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2017
    form_of_study: "contract"
    file_name: "20170729 бви.pdf"
    regex:
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'

  - year: 2018
    form_of_study: "budget"
    file_name: "2018-08-03 бюджет.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2018
    form_of_study: "budget"
    file_name: "2018-08-08 бюджет.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2018
    form_of_study: "paid"
    file_name: "2018-08-08-p-rus платное.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2018
    form_of_study: "paid"
    file_name: "2018-08-31-p-rus платное.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2018
    form_of_study: "contract"
    file_name: "2018-07-29 бви.pdf"
    regex:
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'

  - year: 2019
    form_of_study: "budget"
    file_name: "2019-08-03бюджет.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2019
    form_of_study: "budget"
    file_name: "2019-08-08бюджет.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2019
    form_of_study: "paid"
    file_name: "2019-08-08-p-f-платная.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2019
    form_of_study: "paid"
    file_name: "2019-08-08-p-платная.pdf"
    regex: 
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  - year: 2019
    form_of_study: "contract"
    file_name: "2019-07-29бви.pdf"
    regex:
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
      - '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'