docs:
  # - year: 2016
  #   form_of_study: "budget"
  #   file_name: "03082016.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'

  # - year: 2016
  #   form_of_study: "budget"
  #   file_name: "08082016 бюджет.pdf"  
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'

  # - year: 2016
  #   form_of_study: "paid"
  #   file_name: "08082016p платное.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'

  # - year: 2016
  #   form_of_study: "paid"
  #   file_name: "31082016p платное.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'

  # - year: 2016
  #   form_of_study: "contract"
  #   file_name: "29072016 бви.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'
  #         - 'company'
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'

  # - year: 2017
  #   form_of_study: "budget"
  #   file_name: "20170803 бюджет.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'

  # - year: 2017
  #   form_of_study: "budget"
  #   file_name: "20170808 бюджет.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'

  # - year: 2017
  #   form_of_study: "paid"
  #   file_name: "20170808_p_ платное.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'

  # - year: 2017
  #   form_of_study: "contract"
  #   file_name: "20170729 бви.pdf"
  #   regexes: 
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'
  #         - 'exam_scores'
  #         - 'company'
  #     - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'
  #       model:
  #         - 'last_name'
  #         - 'first_name'
  #         - 'mid_name'
  #         - 'id_abitur'
  #         - 'id_stud'
  #         - 'group_adm'

  - year: 2018
    form_of_study: "budget"
    file_name: "2018-08-03 бюджет.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2018
    form_of_study: "budget"
    file_name: "2018-08-08 бюджет.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2018
    form_of_study: "paid"
    file_name: "2018-08-08-p-rus платное.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2018
    form_of_study: "paid"
    file_name: "2018-08-31-p-rus платное.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2018
    form_of_study: "contract"
    file_name: "2018-07-29 бви.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'
          - 'company'
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'

  - year: 2019
    form_of_study: "budget"
    file_name: "2019-08-03бюджет.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2019
    form_of_study: "budget"
    file_name: "2019-08-08бюджет.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2019
    form_of_study: "paid"
    file_name: "2019-08-08-p-f-платная.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2019
    form_of_study: "paid"
    file_name: "2019-08-08-p-платная.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'

  - year: 2019
    form_of_study: "contract"
    file_name: "2019-07-29бви.pdf"
    regexes: 
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+).+лов:\s*(\d+);.+чание:\s+([^;]+)'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'
          - 'exam_scores'
          - 'company'
      - regex: '§\d+\.\s*([а-яА-Я]+)\s*([а-яА-Я]+)\s*([а-яА-Я]+);.+иента\s*№:\s*([^;]+);.+ента\s*№:\s*([^;]+);.+ппа:\s*([а-яА-Я]+[^;]+);'
        model:
          - 'last_name'
          - 'first_name'
          - 'mid_name'
          - 'id_abitur'
          - 'id_stud'
          - 'group_adm'