decree_parser:
  doc_parser_config: '/config/doc_parser_config.yaml'
  decrees_docs_path: '/storage/data/decrees'
web:
  parser:
    min_year: 2018
    max_year: 2019
    exam_min_index: 28
    exam_max_index: 28
    exam_fac_list: '#session-structure > li'
    exam_stud_name: '> td:nth-child(2) > div:nth-child(2) > span:nth-child(1)'
    exam_stud_id: '> td:nth-child(3) > span:nth-child(2)'
    student_exam_list: '.eu-table > tbody> tr'
    student_exam_subj_grades: '> td'
    exam_subj_list: '.eu-table > thead:nth-child(2) > tr:nth-child(1) > th'
    subj: 'html body div#layout div#workarea div#canvas div#right-column div#content div.outerdiv div.innerdiv table.standart_table.progress_students.vertical_hover.table-group thead tr th'
    webvpn_main: 'https://webvpn.bmstu.ru'
    webvpn_sem_main: 'https://webvpn.bmstu.ru/+CSCO+1h75676763663A2F2F72682E6F7A6667682E6568++/modules/progress3/'
    webvpn_ex_main: 'https://webvpn.bmstu.ru/+CSCO+1h75676763663A2F2F72682E6F7A6667682E6568++/modules/session/'
    fac_list_x: '/html/body/div[1]/div[7]/div/div[2]/div/div'
    fac_list_sel: '.eu-tree-root > li'
    std_in_list: 'table.standart_table:nth-child(1) > tbody:nth-child(3) > tr:nth-child(1)'
  groups:
    'ИУ6-31Б': 'group/8e243850-3d75-11e8-9f9b-005056960017/'
    'ИУ6-32Б': 'group/8e282802-3d75-11e8-8869-005056960017/'
    'ИУ6-33Б': 'group/8e2955e2-3d75-11e8-9b85-005056960017/'
    'ИУ6-34Б': 'group/8e2c2f2e-3d75-11e8-a507-005056960017/'
    'ИУ6-35Б': 'group/8e2d07c8-3d75-11e8-94be-005056960017/'
  login1_u: 'https://webvpn.bmstu.ru/+CSCOE+/logon.html'
  login1_1_u: 'https://webvpn.bmstu.ru/+CSCO+1075676763663A2F2F636265676E79332E72682E6F7A6667682E6568++/portal3/login1?back=https://eu.bmstu.ru/'
  login2_x: '/html/body/div[1]/div/a[1]'
  form1:
    usr: 'username'
    pass: 'password_input'
  form2:
    usr: 'username'
    pass: 'password'
  home_u: 'https://webvpn.bmstu.ru/+CSCO+1h75676763663A2F2F72682E6F7A6667682E6568++/modules/progress3/2019-01/'
  subj_x: '/html/body/div[1]/div[7]/div/div[3]/div/div[2]/div/table/thead/tr/th'
  stud_c: 'table.standart_table:nth-child(1) > tbody:nth-child(3) > tr'
  name: 'td[2]/a/nobr/span[3]'
  stud_id: 'td[3]'
search_method_key_name: 'search_meth'
search_methods:
  - 'find'
  - 'find_first'
  - 'find_except'
  - 'find_except_first'
token_arg_name: 'APIKEY'
search_methods_args:
  - 'name'
  - 'last_name'
  - 'mid_name'
  - 'group'
  - 'year_of_admission'
  - 'exam_scores'
search_args_matching:
  'name': 'first_name'
  'last_name': 'last_name'
  'mid_name': 'mid_name'
  'group': 'group'
  'exam_scores': 'exam_scores'